# Numpy Basico
Estudos básicos utilizando o modulo **[Numpy](https://numpy.org/)**

* [np.array](#np.array)
* [np.arange](#np.arange)

Por convenção da comunidade, utilizasse **np** como alias para o modulo.

In [1]:
import numpy as np

## np.array
cria um ndarray baseado no array passado como parametro

## np.arange
cria um ndarray com range definido, possibilitando definir o intervalo entre cada numero


In [2]:
np.arange(10) # Cria um array iniciado em 0 e menor que 10 com intervalor de 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2, 8) # Cria um array iniciado 2 e menor que 8 com intervalor de 1

array([2, 3, 4, 5, 6, 7])

In [4]:
np.arange(2, 8, 3) # Cria um array iniciado em 2 e menor que 8 com intervalor de 3

array([2, 5])