# Numpy Basico
Estudos básicos utilizando o modulo **[Numpy](https://numpy.org/)**

* [np.array](#np.array)
* [np.arange](#np.arange)

Por convenção da comunidade, utilizasse **np** como alias para o modulo.

## Criação de ndarray

In [1]:
import numpy as np

### np.array
Cria um **ndarray** baseado em um *array/tupla* passado como parametro. Os itens do array podem ser outro array para caracterizar um array de N dimensões. Os subníveis precisam ter tamanhos identicos entre si, para que sera criado um array de N dimensões. 
Exemplo: Se for criado um array com 2 dimensões (**linha** X *coluna*), todas as **linhas** precisam ter o mesmo número de *colunas*. Se for criado um array com 3 dimensões (***página*** X **linha** X *coluna*), todas as ***páginas*** precisam ter o mesmo número de **linhas**, e todas as linhas o mesmo número de *colunas*.

In [5]:
np.array([2, 7, 1, 8]) #Cria array de 1 dimensão (Colunas)

array([2, 7, 1, 8])

In [7]:
np.array([[1, 3, 4], [5, 3, 0]]) #Cria array de 2 dimensões (Linhas X Colunas)

array([[1, 3, 4],
       [5, 3, 0]])

In [11]:
np.array(([(2, 0), (4, 5), (6, 3)], [(4, 3), (3, 1), (2, 9)])) #Cria ndarray de 3 dimensões (Paginas X Linhas X Colunas)

array([[[2, 0],
        [4, 5],
        [6, 3]],

       [[4, 3],
        [3, 1],
        [2, 9]]])

In [13]:
np.array(([([3, 5], [0, 7]), ([4, 8], [5, 6]), ([0, 3], [3, 8])], [([4, 5], [3, 1]), ([3, 7], [1, 5]), ([2, 8], [9, 9])])) #Cria ndarray de 4 dimensões (Cubos X Paginas X Linhas X Colunas)

array([[[[3, 5],
         [0, 7]],

        [[4, 8],
         [5, 6]],

        [[0, 3],
         [3, 8]]],


       [[[4, 5],
         [3, 1]],

        [[3, 7],
         [1, 5]],

        [[2, 8],
         [9, 9]]]])

---

### np.arange
cria um ndarray com range definido, possibilitando definir o intervalo entre cada numero


In [2]:
np.arange(10) # Cria um array iniciado em 0 e menor que 10 com intervalor de 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2, 8) # Cria um array iniciado 2 e menor que 8 com intervalor de 1

array([2, 3, 4, 5, 6, 7])

In [4]:
np.arange(2, 8, 3) # Cria um array iniciado em 2 e menor que 8 com intervalor de 3

array([2, 5])

----