# Numpy Basico
Estudos básicos utilizando o modulo **[Numpy](https://numpy.org/)**

* [np.array](#np.array)
* [np.arange](#np.arange)

Por convenção da comunidade, utilizasse **np** como alias para o modulo.

## Criação de ndarray

In [74]:
import numpy as np

### np.array
Cria um **ndarray** baseado em um *array/tupla* passado como parametro. Os itens do array podem ser outro array para caracterizar um array de N dimensões. Os subníveis precisam ter tamanhos identicos entre si, para que sera criado um array de N dimensões. 
Exemplo: Se for criado um array com 2 dimensões (**linha** X *coluna*), todas as **linhas** precisam ter o mesmo número de *colunas*. Se for criado um array com 3 dimensões (***página*** X **linha** X *coluna*), todas as ***páginas*** precisam ter o mesmo número de **linhas**, e todas as linhas o mesmo número de *colunas*.

In [75]:
np.array([2, 7, 1, 8]) #Cria array de 1 dimensão (Colunas)

array([2, 7, 1, 8])

In [76]:
np.array([[1, 3, 4], [5, 3, 0]]) #Cria array de 2 dimensões (Linhas X Colunas)

array([[1, 3, 4],
       [5, 3, 0]])

In [77]:
np.array(([(2, 0), (4, 5), (6, 3)], [(4, 3), (3, 1), (2, 9)])) #Cria ndarray de 3 dimensões (Paginas X Linhas X Colunas)

array([[[2, 0],
        [4, 5],
        [6, 3]],

       [[4, 3],
        [3, 1],
        [2, 9]]])

In [78]:
np.array(([([3, 5], [0, 7]), ([4, 8], [5, 6]), ([0, 3], [3, 8])], [([4, 5], [3, 1]), ([3, 7], [1, 5]), ([2, 8], [9, 9])])) #Cria ndarray de 4 dimensões (Cubos X Paginas X Linhas X Colunas)

array([[[[3, 5],
         [0, 7]],

        [[4, 8],
         [5, 6]],

        [[0, 3],
         [3, 8]]],


       [[[4, 5],
         [3, 1]],

        [[3, 7],
         [1, 5]],

        [[2, 8],
         [9, 9]]]])

---

### np.zeros
Cria um ndarray com todos valores 0 no formato passado como parametro. Como padrão os valores são decimais.

In [79]:
np.zeros(4) #Cria um ndarray de 1 dimensão com 4 colunas preenchidas com 0

array([0., 0., 0., 0.])

In [80]:
np.zeros([4, 3]) #Cria um ndarray de 2 dimensões com 4 colunas e 3 linhas preenchidas com 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.zeros((2, 3, 4)) #Cria um ndarray de 3 dimensões

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

---

### np.ones
Igual o **np.zero**, mas preenche o ndarray com valor 1

In [82]:
np.ones((2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

---

### np.arange
cria um ndarray com range definido, possibilitando definir o intervalo entre cada numero


In [83]:
np.arange(10) # Cria um array iniciado em 0 e menor que 10 com intervalor de 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(2, 8) # Cria um array iniciado 2 e menor que 8 com intervalor de 1

array([2, 3, 4, 5, 6, 7])

In [85]:
np.arange(2, 8, 3) # Cria um array iniciado em 2 e menor que 8 com intervalor de 3

array([2, 5])

----

### np.linspace
Cria um ndarray de 1 dimensão com 50 colunas por padrão com os valores entre os parametros informados

In [86]:
np.linspace(3, 10) #Cria um ndarray com 50 colunas com valores entre 3 e 10


array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [87]:
np.linspace(2, 30, 10) #Cria um ndarray com 10 colunas com valores entre 2 e 30

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ])

---

### np.random
Varias funções para criar um ndarray com números aleatórios

In [88]:
np.random.random((2, 3)) #Cria um array de 2 linhas e 3 colunas com numeros aletórios entre 0 e 1

array([[0.1550837 , 0.34513493, 0.43309951],
       [0.47951243, 0.03815882, 0.94389613]])

In [89]:
np.random.randint(0, 20, (2, 3)) #Cria um ndarray com valores aleatórios entre 0, 20 com 2 linhas e 3 colunas

array([[ 0, 16,  3],
       [ 2,  7, 10]])

---

## Operações Matemáticas
É possivel realizar operações utilizandos os sinais matematicos (+, -, *, /) entre ndarrays

In [90]:
a1 = np.random.randint(0, 10, (2, 3))
a1

array([[7, 9, 7],
       [8, 1, 0]])

In [91]:
a2 = np.random.randint(1, 10, (2, 3))
a2

array([[3, 1, 6],
       [2, 5, 9]])

### Adição

In [92]:
a1 + 10 #Adicionado 10 a todos os valores do ndarray

array([[17, 19, 17],
       [18, 11, 10]])

In [93]:
a1 + a2 #Adicionado os valores do ndarray a2 ao ndarray a1 em suas respectivas posiçoes

array([[10, 10, 13],
       [10,  6,  9]])

### subtração

In [94]:
a1 - 2

array([[ 5,  7,  5],
       [ 6, -1, -2]])

In [95]:
a1 - a2

array([[ 4,  8,  1],
       [ 6, -4, -9]])

In [96]:
a1 * 2

array([[14, 18, 14],
       [16,  2,  0]])

In [97]:
a1 * a2

array([[21,  9, 42],
       [16,  5,  0]])

In [98]:
a1 / 2

array([[3.5, 4.5, 3.5],
       [4. , 0.5, 0. ]])

In [99]:
a1 / a2

array([[2.33333333, 9.        , 1.16666667],
       [4.        , 0.2       , 0.        ]])

In [100]:
((a1 + a2) / 2) * (a1 - a2)

array([[ 20. ,  40. ,   6.5],
       [ 30. , -12. , -40.5]])

In [101]:
a3 = a1 * a2
a3 += 3
a3

array([[24, 12, 45],
       [19,  8,  3]])

---

## Propriedades
Algumas propriedades do ndarray

In [102]:
nd_prop1 = np.arange(20).reshape((4, 5))
nd_prop1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
nd_prop1.shape

(4, 5)

In [104]:
nd_prop1.dtype

dtype('int32')

In [105]:
nd_prop1.ndim

2

In [106]:
nd_prop1.size

20

In [107]:
nd_prop1.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Funções
Algumas funções basicas do ndarray

### ndarray.reshape
Muda as dimensões do ndarray de acordo com parametro

In [108]:
a3 = np.arange(20)
a3 = a3.reshape((4, 5))
a3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
a3 = a3.reshape((2, 2, 5))
a3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### Sum
Retorna a soma de todos os valores do ndarray

In [110]:
a3.sum()

190